# SoC Monitoring Base Image
# Complete embedded Linux image with monitoring and OTA capabilities
# Generic recipe - works on any SoC platform (Rockchip, NXP, TI, Qualcomm, etc.)

SUMMARY = "SoC Monitoring Platform Base Image"
DESCRIPTION = "A complete embedded Linux image with device monitoring, \
crash capture, telemetry collection, and OTA update support. \
Platform-agnostic design works on any SoC with Yocto/OE support."
LICENSE = "MIT"

inherit core-image buildversion mender-artifact

# Set unique image basename to avoid conflicts with other images
IMAGE_BASENAME = "soc-monitoring-image"

# Use unique image link names to prevent deploy conflicts with other images
# This ensures all deployed files (including platform-specific ones) get unique names
IMAGE_LINK_NAME = "${IMAGE_BASENAME}-${MACHINE}"

# For Rockchip machines, ensure unique partition image names
# These are created by rockchip-gpt-img class
ROCKCHIP_GPTIMG_BASENAME = "${IMAGE_BASENAME}"
ROCKCHIP_GPTIMG_LINK_NAME = "${IMAGE_BASENAME}-${MACHINE}"


# Required distro features for this image
REQUIRED_DISTRO_FEATURES = "systemd usrmerge"

# Base image features
IMAGE_FEATURES += " \
    ssh-server-openssh \
    package-management \
    debug-tweaks \
    "

# Core system packages
IMAGE_INSTALL += " \
    packagegroup-core-boot \
    packagegroup-base-extended \
    "

# Networking packages
IMAGE_INSTALL += " \
    networkmanager \
    curl \
    ca-certificates \
    openssl \
    "

# System utilities
IMAGE_INSTALL += " \
    htop \
    procps \
    util-linux \
    coreutils \
    bash \
    gzip \
    jq \
    pv \
    "

# Network test tooling — required by the TETS-ARE interruption suite
# (INT-001..004) and any future test that injects network faults. tc is
# also useful for tunnel + bandwidth diagnostics on production fleets.
#   has_iptables  → iptables binary present (legacy iptables, not nft only)
#   has_tc_netem  → tc binary + sch_netem.ko both available at runtime
IMAGE_INSTALL += " \
    iproute2-tc \
    iptables \
    kernel-module-sch-netem \
    "

# Auto-load sch_netem at boot so `tc qdisc add ... netem ...` works without
# a manual modprobe. The .ko ships via kernel-modules / kernel-module-sch-netem
# above; this just tells systemd-modules-load.service to insmod it on boot.
ROOTFS_POSTPROCESS_COMMAND += "otapulse_enable_netem_autoload;"

otapulse_enable_netem_autoload() {
    install -d ${IMAGE_ROOTFS}${sysconfdir}/modules-load.d
    echo "sch_netem" > ${IMAGE_ROOTFS}${sysconfdir}/modules-load.d/netem.conf
}

# Monitoring and telemetry
# Using memfaultd-bin (shell script version) to avoid Rust build issues
IMAGE_INSTALL += " \
    memfaultd-bin \
    "

# OTA Updates - SoC OTA Agent (Mender-based)
# Provides A/B partition OTA with signature verification
IMAGE_INSTALL += " \
    soc-ota-agent \
    otapulse-firstboot \
    u-boot-fw-utils \
    u-boot-env-config \
    gptfdisk \
    "

# Kernel and debug support
IMAGE_INSTALL += " \
    kernel-modules \
    "

# Systemd and services
IMAGE_INSTALL += " \
    systemd \
    systemd-analyze \
    "

# Time synchronization
IMAGE_INSTALL += " \
    chrony \
    "

# Extra development tools (remove for production)
IMAGE_INSTALL:append = " \
    strace \
    gdb \
    "

# Image size configuration
IMAGE_ROOTFS_SIZE ?= "1048576"
IMAGE_ROOTFS_EXTRA_SPACE = "524288"
IMAGE_OVERHEAD_FACTOR = "1.3"

# Filesystem types - use generic formats, let machine config add platform-specific ones
# Don't hardcode IMAGE_FSTYPES to allow machine/distro flexibility
IMAGE_FSTYPES ?= "wic wic.gz wic.bmap ext4"

# WIC image configuration - A/B partition layout for OTA
WKS_FILE ?= "soc-monitoring.wks.in"

# Disable UFS image creation - not needed for eMMC storage
# This removes the time-consuming do_image_wic_ufs task from rockchip-image.bbclass
IMAGE_POSTPROCESS_COMMAND:remove = "do_image_wic_ufs;"

# Firmware manifest is generated by buildversion class in /etc/build-info
# Do not use shell functions with $(date) or $(git) as they cause non-deterministic hashes

# Ensure proper boot configuration
# Note: remove read-only-rootfs for development, enable for production
# EXTRA_IMAGE_FEATURES += "read-only-rootfs"

# SDK configuration
TOOLCHAIN_TARGET_TASK += "packagegroup-core-standalone-sdk-target"

# Generic systemd configuration - suppress common warnings
# To silence systemd warning about /home/root, add this to your local.conf:
# ROOT_HOME = "/root"

# Added by /verify-remote-ssh remote-ssh integration (TODO-002)
IMAGE_INSTALL:append = " \
    frp \
    soc-ota-tunneld \
    soc-shell-access \
    "
