#!/bin/sh
# Generic U-Boot Environment Setup Script
# Auto-detects SoC type and configures fw_env.config appropriately
# Supports: Rockchip, NXP i.MX, TI AM series, Allwinner, and others

set -e

FW_ENV_CONFIG="/etc/fw_env.config"
BOOT_DEVICE=""
ENV_OFFSET=""
ENV_SIZE="0x8000"  # 32KB default

# Detect boot device
detect_boot_device() {
    # Try to find the boot device from kernel cmdline
    local root_dev=$(cat /proc/cmdline | tr ' ' '\n' | grep "root=" | head -1 | sed 's/root=//')
    
    if echo "$root_dev" | grep -q "PARTUUID"; then
        # Resolve PARTUUID to device
        local partuuid=$(echo "$root_dev" | sed 's/PARTUUID=//')
        root_dev=$(blkid -t PARTUUID="$partuuid" -o device 2>/dev/null | head -1)
    fi
    
    if [ -n "$root_dev" ]; then
        # Get the base device (remove partition number)
        BOOT_DEVICE=$(echo "$root_dev" | sed 's/p[0-9]*$//' | sed 's/[0-9]*$//')
    fi
    
    # Fallback: try common boot devices
    if [ -z "$BOOT_DEVICE" ] || [ ! -b "$BOOT_DEVICE" ]; then
        for dev in /dev/mmcblk0 /dev/mmcblk1 /dev/sda; do
            if [ -b "$dev" ]; then
                BOOT_DEVICE="$dev"
                break
            fi
        done
    fi
    
    echo "Detected boot device: $BOOT_DEVICE"
}

# Detect SoC type and set environment offset
detect_soc_and_offset() {
    local soc_type="unknown"
    local model=""
    
    # Try to detect from device tree
    if [ -f /proc/device-tree/compatible ]; then
        local compat=$(cat /proc/device-tree/compatible | tr '\0' '\n' | head -5)
        
        if echo "$compat" | grep -qi "rockchip"; then
            soc_type="rockchip"
        elif echo "$compat" | grep -qi "fsl,imx\|nxp,imx"; then
            soc_type="imx"
        elif echo "$compat" | grep -qi "ti,am\|ti,omap"; then
            soc_type="ti"
        elif echo "$compat" | grep -qi "allwinner"; then
            soc_type="allwinner"
        elif echo "$compat" | grep -qi "amlogic"; then
            soc_type="amlogic"
        elif echo "$compat" | grep -qi "broadcom,bcm\|brcm,bcm"; then
            soc_type="broadcom"
        fi
    fi
    
    # Also check model
    if [ -f /proc/device-tree/model ]; then
        model=$(cat /proc/device-tree/model | tr '\0' ' ')
    fi
    
    echo "Detected SoC type: $soc_type"
    echo "Model: $model"
    
    # Set offset based on SoC type
    case "$soc_type" in
        rockchip)
            # Rockchip: U-Boot env typically at 0x3F8000 (4MB - 32KB)
            # or in the uboot partition
            ENV_OFFSET="0x3F8000"
            ENV_SIZE="0x8000"
            ;;
        imx)
            # NXP i.MX: Usually at 0x400000
            ENV_OFFSET="0x400000"
            ENV_SIZE="0x4000"
            ;;
        ti)
            # TI AM series: Usually at 0x260000
            ENV_OFFSET="0x260000"
            ENV_SIZE="0x20000"
            ;;
        allwinner)
            # Allwinner: Usually at 0x88000
            ENV_OFFSET="0x88000"
            ENV_SIZE="0x8000"
            ;;
        amlogic)
            # Amlogic: Usually in dedicated partition
            ENV_OFFSET="0x7400000"
            ENV_SIZE="0x10000"
            ;;
        *)
            # Default: Try common offset
            ENV_OFFSET="0x3F8000"
            ENV_SIZE="0x8000"
            ;;
    esac
    
    echo "Environment offset: $ENV_OFFSET, size: $ENV_SIZE"
}

# Generate fw_env.config
generate_config() {
    cat > "$FW_ENV_CONFIG" << EOF
# U-Boot Environment Configuration
# Auto-generated by setup-uboot-env.sh
# Device: $BOOT_DEVICE
# Offset: $ENV_OFFSET
# Size: $ENV_SIZE

$BOOT_DEVICE	$ENV_OFFSET	$ENV_SIZE
EOF
    
    chmod 644 "$FW_ENV_CONFIG"
    echo "Generated $FW_ENV_CONFIG"
}

# Verify configuration works
verify_config() {
    if command -v fw_printenv >/dev/null 2>&1; then
        echo "Testing fw_printenv..."
        if fw_printenv >/dev/null 2>&1; then
            echo "SUCCESS: U-Boot environment is accessible"
            return 0
        else
            echo "WARNING: fw_printenv failed - environment may be at different offset"
            return 1
        fi
    else
        echo "fw_printenv not available"
        return 1
    fi
}

# Main
main() {
    echo "=== U-Boot Environment Setup ==="
    
    detect_boot_device
    
    if [ -z "$BOOT_DEVICE" ] || [ ! -b "$BOOT_DEVICE" ]; then
        echo "ERROR: Could not detect boot device"
        exit 1
    fi
    
    detect_soc_and_offset
    generate_config
    verify_config || echo "Manual configuration may be required"
    
    echo "=== Setup Complete ==="
}

main "$@"
